name: PVPArena
main: dannikinfo.pvparena.PVPArena
author: dannikinfo
version: ${version}

commands:
   pa:
      description: базовая команда арен
      permission: <plugin name>.pa
      usage: /<command>